### ISSUE TITLE
Clarify whether this supports ejected expo projects

### ISSUE THREAD

**Issue by quincycs** [mglagola/exptool#1]
Hi,

Can you clarify whether this supports ejected expo projects?  Thanks!! Sounds great either way.

**Comment by mglagola** [comment]
@quincycs **This tool does not support ejected expo projects.**

However, If you are looking to automate your build process, [fastlane](http://fastlane.tools) _should_ work out of the box with "pure" react-native projects (including _ExpoKit_ projects).
